name: Rebuild Erlang 26.2 on RockyLinux 9 image

on:
  push:
    branches: ['main']
    paths: ['dockerfiles/26.2-rocky9/Dockerfile', '.github/workflows/image-26.2-rocky9.yml']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: dockerfiles/26.2-rocky9/Dockerfile
          # Building for amd64 only to reduce build time
          platforms: linux/amd64
          push: true
          tags: rabbitmqdevenv/build-env-26.2-rocky9:latest
